// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresdriver

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/vishruthsk/portal-db-main/types"
)

type PermissionsEnum string

const (
	PermissionsEnumReadEndpoint  PermissionsEnum = "read:endpoint"
	PermissionsEnumWriteEndpoint PermissionsEnum = "write:endpoint"
)

func (e *PermissionsEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionsEnum(s)
	case string:
		*e = PermissionsEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionsEnum: %T", src)
	}
	return nil
}

type NullPermissionsEnum struct {
	PermissionsEnum PermissionsEnum
	Valid           bool // Valid is true if PermissionsEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionsEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionsEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionsEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionsEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.PermissionsEnum, nil
}

type AppLimit struct {
	ID            int32         `json:"id"`
	ApplicationID string        `json:"applicationID"`
	PayPlan       string        `json:"payPlan"`
	CustomLimit   sql.NullInt32 `json:"customLimit"`
}

type Application struct {
	ID                 sql.NullInt32  `json:"id"`
	ApplicationID      string         `json:"applicationID"`
	ContactEmail       sql.NullString `json:"contactEmail"`
	Description        sql.NullString `json:"description"`
	Name               sql.NullString `json:"name"`
	Status             sql.NullString `json:"status"`
	Owner              sql.NullString `json:"owner"`
	Url                sql.NullString `json:"url"`
	UserID             sql.NullString `json:"userID"`
	Dummy              sql.NullBool   `json:"dummy"`
	FirstDateSurpassed sql.NullTime   `json:"firstDateSurpassed"`
	CreatedAt          sql.NullTime   `json:"createdAt"`
	UpdatedAt          sql.NullTime   `json:"updatedAt"`
}

type Blockchain struct {
	ID                sql.NullInt32  `json:"id"`
	BlockchainID      string         `json:"blockchainID"`
	Active            sql.NullBool   `json:"active"`
	Altruist          sql.NullString `json:"altruist"`
	Blockchain        sql.NullString `json:"blockchain"`
	BlockchainAliases []string       `json:"blockchainAliases"`
	ChainID           sql.NullString `json:"chainID"`
	ChainIDCheck      sql.NullString `json:"chainIDCheck"`
	Description       sql.NullString `json:"description"`
	EnforceResult     sql.NullString `json:"enforceResult"`
	LogLimitBlocks    sql.NullInt32  `json:"logLimitBlocks"`
	Network           sql.NullString `json:"network"`
	Path              sql.NullString `json:"path"`
	RequestTimeout    sql.NullInt32  `json:"requestTimeout"`
	Ticker            sql.NullString `json:"ticker"`
	CreatedAt         sql.NullTime   `json:"createdAt"`
	UpdatedAt         sql.NullTime   `json:"updatedAt"`
}

type GatewayAat struct {
	ID              int32          `json:"id"`
	ApplicationID   string         `json:"applicationID"`
	Address         string         `json:"address"`
	PublicKey       string         `json:"publicKey"`
	PrivateKey      sql.NullString `json:"privateKey"`
	Signature       string         `json:"signature"`
	ClientPublicKey string         `json:"clientPublicKey"`
	Version         sql.NullString `json:"version"`
}

type GatewaySetting struct {
	ID                   int32          `json:"id"`
	ApplicationID        string         `json:"applicationID"`
	SecretKey            sql.NullString `json:"secretKey"`
	SecretKeyRequired    sql.NullBool   `json:"secretKeyRequired"`
	WhitelistBlockchains []string       `json:"whitelistBlockchains"`
	WhitelistOrigins     []string       `json:"whitelistOrigins"`
	WhitelistUserAgents  []string       `json:"whitelistUserAgents"`
}

type LbApp struct {
	ID    int32  `json:"id"`
	LbID  string `json:"lbID"`
	AppID string `json:"appID"`
}

type Loadbalancer struct {
	ID                int32          `json:"id"`
	LbID              string         `json:"lbID"`
	UserID            sql.NullString `json:"userID"`
	Name              sql.NullString `json:"name"`
	RequestTimeout    sql.NullInt32  `json:"requestTimeout"`
	Gigastake         sql.NullBool   `json:"gigastake"`
	GigastakeRedirect sql.NullBool   `json:"gigastakeRedirect"`
	CreatedAt         sql.NullTime   `json:"createdAt"`
	UpdatedAt         sql.NullTime   `json:"updatedAt"`
}

type NotificationSetting struct {
	ID              int32        `json:"id"`
	ApplicationID   string       `json:"applicationID"`
	SignedUp        sql.NullBool `json:"signedUp"`
	OnQuarter       sql.NullBool `json:"onQuarter"`
	OnHalf          sql.NullBool `json:"onHalf"`
	OnThreeQuarters sql.NullBool `json:"onThreeQuarters"`
	OnFull          sql.NullBool `json:"onFull"`
}

type PayPlan struct {
	ID         sql.NullInt32 `json:"id"`
	PlanType   string        `json:"planType"`
	DailyLimit int32         `json:"dailyLimit"`
	CreatedAt  sql.NullTime  `json:"createdAt"`
	UpdatedAt  sql.NullTime  `json:"updatedAt"`
}

type Redirect struct {
	ID           int32        `json:"id"`
	BlockchainID string       `json:"blockchainID"`
	Alias        string       `json:"alias"`
	Loadbalancer string       `json:"loadbalancer"`
	Domain       string       `json:"domain"`
	CreatedAt    sql.NullTime `json:"createdAt"`
	UpdatedAt    sql.NullTime `json:"updatedAt"`
}

type StickinessOption struct {
	ID         int32          `json:"id"`
	LbID       string         `json:"lbID"`
	Duration   sql.NullString `json:"duration"`
	StickyMax  sql.NullInt32  `json:"stickyMax"`
	Stickiness sql.NullBool   `json:"stickiness"`
	Origins    []string       `json:"origins"`
}

type SyncCheckOption struct {
	ID           int32          `json:"id"`
	BlockchainID string         `json:"blockchainID"`
	Synccheck    sql.NullString `json:"synccheck"`
	Allowance    sql.NullInt32  `json:"allowance"`
	Body         sql.NullString `json:"body"`
	Path         sql.NullString `json:"path"`
	ResultKey    sql.NullString `json:"resultKey"`
}

type UserAccess struct {
	ID        int32          `json:"id"`
	LbID      sql.NullString `json:"lbID"`
	UserID    sql.NullString `json:"userID"`
	RoleName  sql.NullString `json:"roleName"`
	Email     sql.NullString `json:"email"`
	Accepted  sql.NullBool   `json:"accepted"`
	CreatedAt sql.NullTime   `json:"createdAt"`
	UpdatedAt sql.NullTime   `json:"updatedAt"`
}

type UserRole struct {
	ID          sql.NullInt32           `json:"id"`
	Name        string                  `json:"name"`
	Permissions []types.PermissionsEnum `json:"permissions"`
	CreatedAt   sql.NullTime            `json:"createdAt"`
	UpdatedAt   sql.NullTime            `json:"updatedAt"`
}

type WhitelistContract struct {
	ID            int32          `json:"id"`
	ApplicationID string         `json:"applicationID"`
	BlockchainID  sql.NullString `json:"blockchainID"`
	Contracts     []string       `json:"contracts"`
}

type WhitelistMethod struct {
	ID            int32          `json:"id"`
	ApplicationID string         `json:"applicationID"`
	BlockchainID  sql.NullString `json:"blockchainID"`
	Methods       []string       `json:"methods"`
}
